title: Charitha Saumya
#url: ""
#baseurl: "/charitha22.github.io"
url: "charitha22.github.io"
baseurl: "/"

markdown: kramdown

github: "charitha22"
linkedin: "charithasaumya"
twitter: "charitha22"
mail: "cgusthin@purdue.edu"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "github"
  - name: "linkedin"
  - name: "twitter"
  - name: "mail"
